// Generated by argus_skill.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.1+965d08586c5f6618";
export const RELEASE_SOURCE_DIGEST = "965d08586c5f66188476226ea1ee556d357a19e7c934069a240aab712af48c0b";
