// Generated by argus_skill.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.1+456a3b34ab47a1ff";
export const RELEASE_SOURCE_DIGEST = "456a3b34ab47a1ffc2d1d393ec5ae1655b667123af8e701f6678690334fd4d1b";
