// Generated by argus_skill.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.1+c04044e082f1cf46";
export const RELEASE_SOURCE_DIGEST = "c04044e082f1cf46ddeb5c6475b6877d6a57b08b20a37c3201787949c724a9ef";
